---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 120 seconds for target connection to become reachable/usable."
      command: 'sleep 120'

    - name: "install dependences"
      apt:
        name: [ "unzip" ]
        state: latest
        update_cache: yes

  roles:
    - awscli
    - kubectl

- name: "config kubectl"
  hosts: web
  user: ubuntu
  gather_facts: false
  become: true
  become_user: root
  pre_tasks:
    # To update a kubeconfig for your cluster
    - name: To update a kubeconfig for your cluster
      shell: "aws eks update-kubeconfig --region us-east-1 --name prj5-kuber"
