- name: "Deploy application"
  hosts: web[0]
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    CIRCLE_WORKFLOW_ID: "{{ lookup('env', 'CIRCLE_WORKFLOW_ID') }}"
  tasks:
    - name: build
      shell: "./bin/kubectl set image deployments/prj5-deploy prj5-app=shalltearbloodfallen01/prj5-deploy:{{ CIRCLE_WORKFLOW_ID }}"
      args:
        chdir: $HOME

    - name: get pods
      shell: "./bin/kubectl -n prj5-deploy get events --sort-by='{.lastTimestamp}'"
      args:
        chdir: $HOME      

    # - name: get namspace
    #   shell: "./bin/kubectl get events --all-namespaces"
    #   args:
    #     chdir: $HOME

    # - name: describe
    #   shell: "./bin/kubectl get deployment"
    #   args:
    #     chdir: $HOME

    # - name: get pods
    #   shell: "./bin/kubectl get pods"
    #   args:
    #     chdir: $HOME      

    - name: if successful
      shell: "./bin/kubectl rollout status deployments/prj5-deploy --timeout=120s"
      args:
        chdir: $HOME