Description: >
    Carlos Rivas / Udacity 2019
Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

Resources:

  # create role for cluster
  EKSRoleCustom:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-roles
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess

  # Instance Profile
  RootInstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      InstanceProfileName: !Sub ${EnvironmentName}-cluster-profile
      Path: "/"
      Roles: 
        - Ref: "EKSRoleCustom"


  # create cluster
  CapstoneProjectCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Sub ${EnvironmentName}-cluster
      RoleArn: !GetAtt EKSRoleCustom.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${EnvironmentName}-SecurityGroupIds
        SubnetIds:
          Fn::Split:
            - ","
            - Fn::ImportValue:
                Fn::Sub: ${EnvironmentName}-PUB-NETS

Outputs:
  EksId:
    Description: EKS id
    Value: !Ref CapstoneProjectCluster
    Export:
      Name: !Sub ${EnvironmentName}-EKSCluster

  EKSRoleArn:
    Description: Role for accessing and creating aws resources
    Value: !GetAtt EKSRoleCustom.Arn
    Export:
      Name: !Sub ${EnvironmentName}-EKSRole