Description: >
    Carlos Rivas / Udacity 2019
Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Default: prj5
    Type: String

Resources:

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-management-SG
      GroupDescription: Allow port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  managementHost1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udapeople
      ImageId: ami-095577d5f61619e4b
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-management1
        - Key: Project
          Value: !Ref EnvironmentName

  managementHost2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udapeople
      ImageId: ami-095577d5f61619e4b
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-management2
        - Key: Project
          Value: !Ref EnvironmentName