version: 2.1


jobs:
  lint:
    docker:
      - image: python:3.7.3-stretch

    steps:
      - checkout

      # make install
      - run:
          name: active env
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install

            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      # make lint
      - run:
          name: make lint
          command: |
            . venv/bin/activate
            make lint
      - save_cache:
          paths:
            - ./venv
          key: linter

  docker-push:
    docker:
      - image: python:3.7.3-stretch

    steps:
      - checkout
      # Creates a remote Docker environment configured to execute Docker commands.
      - setup_remote_docker 

      - run:
        name: build image docker
        command: |
          docker build --tag=prj5 .
          docker image ls

      - run:
        name: push to Docker Hub
        command: |
            docker login -u shalltearbloodfallen01 -p Long3900@
            docker tag prj5 shalltearbloodfallen01/prj5:v1
            docker push shalltearbloodfallen01/prj5:v1



workflows:
  default:
    jobs:
      - lint