- name: configuration
  copy:
    src: "{{ ENVIRONMENT_NAME }}-deployment.yaml"
    dest: $HOME

- name: apply deployment
  shell: "./bin/kubectl apply -f {{ ENVIRONMENT_NAME }}-deployment.yaml"
  args:
    chdir: $HOME
