---
- name: "download"
  shell: curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
  args:
    chdir: $HOME

- name: "apply"
  shell: chmod +x ./kubectl
  args:
    chdir: $HOME

- name: "copy to path"
  shell: mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
  args:
    chdir: $HOME

- name: "add home shell"
  shell: echo 'export PATH=$PATH:$HOME/bin' >> .bashrc
  args:
    chdir: $HOME
