---
- name: "download"
  shell: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  args:
    chdir: $HOME

- name: "unzip"
  shell: unzip awscliv2.zip
  args:
    chdir: $HOME

- name: "Install the AWS CLI"
  shell: ./aws/install
  args:
    chdir: $HOME
