- name: configuration
  copy:
    src: "{{ ENVIRONMENT_NAME }}-service.yaml"
    dest: $HOME

- name: create service
  command: "./bin/kubectl apply -f {{ ENVIRONMENT_NAME }}-service.yaml"
  args:
    chdir: $HOME
