apiVersion: apps/v1
kind: Deployment
metadata:
  name: prj5-deploy
  labels:
    app: prj5-app
spec:
  paused: false
  replicas: 4
  selector:
    matchLabels:
      app: prj5-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
  template:
    metadata:
      labels:
        app: prj5-app
      
    spec:
      containers:
        - name: prj5-app
          image: shalltearbloodfallen01/prj5-deploy
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            successThreshold: 3
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
          # ports:
          #   - containerPort: 80